function loadAdminDashboard(){
 const cs=getDB().complaints; document.getElementById("aTotal").textContent=cs.length;document.getElementById("aPending").textContent=cs.filter(c=>c.status==="Submitted").length;document.getElementById("aProgress").textContent=cs.filter(c=>c.status==="In Progress"||c.status==="Assigned"||c.status==="Verified").length;document.getElementById("aResolved").textContent=cs.filter(c=>c.status==="Resolved").length;document.getElementById("aBreached").textContent=cs.filter(c=>new Date(c.deadline)<new Date()&&c.status!=="Resolved").length;
 document.getElementById("adminRecent").innerHTML=cs.slice(-5).reverse().map(c=>`<div class="admin-row"><div class="admin-row-main"><h3>${escapeHTML(c.id)} • ${escapeHTML(c.category)}</h3><p>${escapeHTML(c.location)}</p></div><span class="pill ${statusClass(c.status)}">${escapeHTML(c.status)}</span></div>`).join("");
 const counts={};cs.forEach(c=>counts[c.category]=(counts[c.category]||0)+1);const max=Math.max(1,...Object.values(counts));
 document.getElementById("analytics").innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v])=>`<div class="analytics-bar"><div class="analytics-label"><span>${escapeHTML(k)}</span><strong>${v}</strong></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join("");
}
function setupAdminComplaints(){
 const render=()=>{const db=getDB(),users=db.users,q=document.getElementById("adminSearch").value.toLowerCase(),f=document.getElementById("statusFilter").value,all=db.complaints,open=all.filter(c=>c.status!=="Resolved"),breaches=open.filter(c=>new Date(c.deadline)<new Date());document.getElementById("caseTotal").textContent=all.length;document.getElementById("caseOpen").textContent=open.length;document.getElementById("caseSla").textContent=breaches.length;const cs=all.filter(c=>(!f||c.status===f)&&(`${c.id} ${c.category} ${c.location} ${c.description} ${users.find(u=>u.id===c.userId)?.name||""}`).toLowerCase().includes(q));document.getElementById("adminComplaints").innerHTML=cs.map(c=>{const citizen=users.find(u=>u.id===c.userId),breached=new Date(c.deadline)<new Date()&&c.status!=="Resolved";return `<div class="admin-row panel"><div class="admin-row-main"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><h3>${escapeHTML(c.id)} • ${escapeHTML(c.category)}</h3><span class="pill ${statusClass(c.status)}">${escapeHTML(c.status)}</span><span class="pill ${breached?"danger":"neutral"}">${breached?"SLA Breached":"SLA Active"}</span></div><p>📍 ${escapeHTML(c.location)} · 👤 ${escapeHTML(citizen?.name||"Unknown")}</p><p>Reported: ${formatDate(c.createdAt)} · Department: ${escapeHTML(c.department)} · Deadline: ${formatDate(c.deadline)}</p><p>${escapeHTML(c.description.slice(0,150))}${c.description.length>150?"…":""}</p></div><div class="admin-row-actions"><button class="btn secondary" onclick="openComplaint('${c.id}')">View case</button><button class="btn primary" onclick="quickNext('${c.id}')">${c.status==="Resolved"?"Resolved":"Next status"} →</button></div></div>`;}).join("")||"<div class='panel'>No matching complaints.</div>";};
 document.getElementById("adminSearch").addEventListener("input",render);document.getElementById("statusFilter").addEventListener("change",render);render();
}
function openComplaint(id){const c=getDB().complaints.find(x=>x.id===id);if(!c)return;const users=getDB().users,u=users.find(x=>x.id===c.userId);const stages=["Submitted","Verified","Assigned","In Progress","Resolved"],idx=stages.indexOf(c.status);const timeline=stages.map((s,i)=>`<div class="workflow-step ${i<=idx?'done':''}"><i>${i<=idx?'✓':i+1}</i><span>${s}</span></div>`).join('');const html=`<div class="modal-backdrop" id="modal"><div class="modal case-modal"><div class="case-header"><div><span class="eyebrow">CIVIC CASE</span><h2>${escapeHTML(c.id)} · ${escapeHTML(c.category)}</h2></div><button class="icon-btn" onclick="closeModal()">✕</button></div><p class="case-description">${escapeHTML(c.description)}</p><div class="case-details"><div><span>Citizen</span><strong>${escapeHTML(u?.name||"Unknown")}</strong></div><div><span>Location</span><strong>📍 ${escapeHTML(c.location)}</strong></div></div><div class="evidence-box">${c.photo?`<img src="${c.photo}" alt="Complaint evidence">`:`<div class="no-photo"><span>🖼️</span><strong>No photo attached</strong><small>Citizen did not upload evidence for this report.</small></div>`}</div><div class="workflow-card"><h3>Workflow</h3><div class="workflow-line">${timeline}</div></div><div class="case-form-grid"><label>Department<select id="departmentSelect"><option>Road Maintenance</option><option>Sanitation</option><option>Electricity</option><option>Water Department</option><option>Animal Control</option><option>Public Safety</option></select></label><label>Status<select id="statusSelect"><option>Submitted</option><option>Verified</option><option>Assigned</option><option>In Progress</option><option>Resolved</option></select></label></div><div class="case-footer"><small>Reported ${formatDate(c.createdAt)} · SLA deadline ${formatDate(c.deadline)}</small><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAdminUpdate('${c.id}')">Save Update</button></div></div></div></div>`;document.body.insertAdjacentHTML('beforeend',html);document.getElementById('statusSelect').value=c.status;document.getElementById('departmentSelect').value=c.department==='Unassigned'?'Road Maintenance':c.department;}
function closeModal(){document.getElementById("modal")?.remove();}
function saveAdminUpdate(id){const status=document.getElementById("statusSelect").value,dept=document.getElementById("departmentSelect").value,c=getDB().complaints.find(x=>x.id===id);const patch={status,department:dept};if(status==="Resolved"){patch.resolvedAt=new Date().toISOString();patch.resolution="Issue inspected and marked resolved by the municipal team."}updateComplaint(id,patch);addNotification(c.userId,`${id} status updated to ${status}.`);const db=getDB(),u=db.users.find(x=>x.id===c.userId);if(status==="Resolved"&&!u.badges.includes("Civic Reporter"))u.badges.push("Civic Reporter");if(status==="Resolved"&&u.points<140)u.points=140;saveDB(db);closeModal();showToast(`${id} updated to ${status}`);setupAdminComplaints();}
function quickNext(id){const stages=["Submitted","Verified","Assigned","In Progress","Resolved"],c=getDB().complaints.find(x=>x.id===id),i=stages.indexOf(c.status),next=stages[Math.min(i+1,stages.length-1)];const patch={status:next};if(next!=="Submitted")patch.department=c.department==="Unassigned"?"Road Maintenance":c.department;if(next==="Resolved"){patch.resolvedAt=new Date().toISOString();patch.resolution="Issue inspected and marked resolved by the municipal team."}updateComplaint(id,patch);addNotification(c.userId,`${id} status updated to ${next}.`);const db=getDB(),u=db.users.find(x=>x.id===c.userId);if(next==="Resolved"&&!u.badges.includes("Civic Reporter"))u.badges.push("Civic Reporter");if(next==="Resolved")u.points=Math.max(u.points,140);saveDB(db);showToast(`${id} → ${next}`);setupAdminComplaints();}
